#!/usr/bin/env node
'use strict';
const fs = require('fs');
const path = require('path');
const root = __dirname;
const checks = [];
const check = (name, ok, detail='') => checks.push({name, pass:Boolean(ok), detail});
const read = rel => fs.readFileSync(path.join(root, rel), 'utf8');
const workspace = read('assets/js/agent-workspace.js');
const motion = read('assets/js/workspace-motion.js');
const workspaceCss = read('agent/workspace/workspace.css');
const property = read('assets/js/property-intelligence.js');
const attribution = read('assets/js/attribution.js');
const allJs = [];
(function walk(dir){ for(const ent of fs.readdirSync(dir,{withFileTypes:true})){ const p=path.join(dir,ent.name); if(ent.isDirectory() && !['node_modules','.git'].includes(ent.name)) walk(p); else if(ent.isFile() && ent.name.endsWith('.js') && !ent.name.endsWith('_QA.js') && ent.name !== 'RUN_REGRESSION_SUITE.js') allJs.push(p); }})(root);
const joined = allJs.map(p=>fs.readFileSync(p,'utf8')).join('\n');
check('safe UUID lookup in Property Intelligence', /window\.crypto/.test(property) && !/\bcrypto\?\./.test(property));
check('safe UUID lookup in Attribution', /window\.crypto/.test(attribution) && !/if \(crypto &&/.test(attribution));
check('matchMedia guarded', /typeof global\.matchMedia !== 'function'/.test(motion));
check('legacy MediaQueryList listener fallback', /query\.addListener/.test(motion) && /query\.removeListener/.test(motion));
check('animation-frame fallback exists', /typeof global\.requestAnimationFrame === 'function'/.test(motion) && /global\.setTimeout/.test(motion));
check('scrollIntoView compatibility fallback exists', /element\.scrollIntoView\(settings\)/.test(workspace) && /element\.scrollIntoView\(\)/.test(workspace));
check('reduced-motion-aware scrolling exists', /prefersReducedMotion/.test(workspace));
check('viewport height fallback precedes dvh enhancement', /max-height:\s*min\(78vh/.test(workspaceCss) && /max-height:\s*min\(78dvh/.test(workspaceCss));
check('iOS momentum scrolling enabled', /-webkit-overflow-scrolling:\s*touch/.test(workspaceCss));
check('forced-colors support exists', /@media\s*\(forced-colors:\s*active\)/.test(workspaceCss));
check('reduced-motion CSS exists', /prefers-reduced-motion:\s*reduce/.test(workspaceCss));
check('no required ResizeObserver dependency', !/\bResizeObserver\b/.test(joined));
check('no required IntersectionObserver dependency', !/\bIntersectionObserver\b/.test(joined));
check('no required structuredClone dependency', !/\bstructuredClone\b/.test(joined));
check('no required requestIdleCallback dependency', !/\brequestIdleCallback\b/.test(joined));
check('no required dialog showModal dependency', !/\.showModal\s*\(/.test(joined));
check('no required inert property dependency', !/\.inert\s*=|setAttribute\(['\"]inert/.test(joined));
const htmlFiles=[];
(function walkHtml(dir){ for(const ent of fs.readdirSync(dir,{withFileTypes:true})){ const p=path.join(dir,ent.name); if(ent.isDirectory() && !['node_modules','.git'].includes(ent.name)) walkHtml(p); else if(ent.isFile() && ent.name.endsWith('.html')) htmlFiles.push(p); }})(root);
check('all HTML documents declare language', htmlFiles.every(p=>/<html[^>]+lang=["'][^"']+["']/i.test(fs.readFileSync(p,'utf8'))));
check('all HTML documents define responsive viewport', htmlFiles.every(p=>/<meta[^>]+name=["']viewport["']/i.test(fs.readFileSync(p,'utf8'))));
const failed=checks.filter(c=>!c.pass);
console.log(JSON.stringify({suite:'WR-1C.3 Cross-Browser Compatibility',version:read('VERSION').trim(),total:checks.length,passed:checks.length-failed.length,failed:failed.length,checks},null,2));
process.exit(failed.length?1:0);
